truck/views/answer_views.py
from datetime import datetime

from flask import Blueprint, url_for, request, render_template, jsonify, session, g, flash
from werkzeug.utils import redirect

from truck import db
from ..forms import AnswerForm
from truck.models import Category, Question, Answer, User
from .auth_views import login_required
import markdown
from markupsafe import Markup

bp = Blueprint('answer', __name__, url_prefix='/answer')

"""
@bp.route('/create/<int:question_id>', methods=('POST',))
@login_required
def create(question_id):
    form = AnswerForm()
    question = Question.query.get_or_404(question_id)

    # 페이지 번호를 URL 매개변수로부터 받음, 기본값은 1
    page = request.args.get('page', type=int, default=1)

    # 답변을 페이징 처리하여 5개씩 출력
    answers = question.answer_set.order_by(Answer.create_date.asc()).paginate(page, per_page=5)

    if form.validate_on_submit():
        content = request.form['content']
        answer = Answer(content=content, create_date=datetime.now(), user=g.user)
        question.answer_set.append(answer)
        db.session.commit()

        return redirect('{}#answer_{}'.format(
            url_for('question.detail', question_id=question_id, page=page), answer.id))

    return render_template('question/question_detail.html', question=question, answers=answers, form=form)
"""

@bp.route('/create/<int:question_id>', methods=('POST',))
@login_required
def create(question_id):
    form = AnswerForm()
    question = Question.query.get_or_404(question_id)

    if form.validate_on_submit():
        content = request.form['content']
        answer = Answer(content=content, create_date=datetime.now(), user=g.user, question_id=question_id)
        db.session.add(answer)
        db.session.commit()

        return redirect('{}#answer_{}'.format(
            url_for('question.detail', question_id=question_id), answer.id))

    # Answer 모델에 대해 직접 쿼리를 수행하여 정렬 및 페이징
    page = request.args.get('page', type=int, default=1)
    answers = Answer.query.filter_by(question_id=question.id)\
                          .order_by(Answer.create_date.asc())\
                          .paginate(page, per_page=5)

    return render_template('question/question_detail.html', question=question, answers=answers, form=form)



@bp.route('/modify/<int:answer_id>', methods=('GET', 'POST'))
@login_required
def modify(answer_id):
    answer = Answer.query.get_or_404(answer_id)
    if g.user != answer.user:
        flash('수정권한이 없습니다')
        return redirect(url_for('question.detail', question_id=answer.question.id))

    if request.method == "POST":
        form = AnswerForm()
        if form.validate_on_submit():
            form.populate_obj(answer)
            answer.modify_date = datetime.now()  # 수정일시 저장
            db.session.commit()

            return redirect('{}#answer_{}'.format(
                url_for('question.detail', question_id=answer.question.id), answer.id))
    else:
        form = AnswerForm(obj=answer)

    return render_template('answer/answer_form.html', form=form)


@bp.route('/delete/<int:answer_id>')
@login_required
def delete(answer_id):
    answer = Answer.query.get_or_404(answer_id)
    question_id = answer.question.id
    if g.user != answer.user:
        flash('삭제권한이 없습니다')
    else:
        db.session.delete(answer)
        db.session.commit()
    return redirect(url_for('question.detail', question_id=question_id))


@bp.route('/vote/<int:answer_id>/', methods=['POST'])  # POST 요청으로 처리
@login_required
def vote(answer_id):
    _answer = Answer.query.get_or_404(answer_id)
    if g.user == _answer.user:
        return jsonify({'success': False, 'message': '본인이 작성한 글은 추천할 수 없습니다.'})
    else:
        _answer.voter.append(g.user)
        db.session.commit()
        return jsonify({'success': True, 'voter_count': len(_answer.voter)})

"""
@bp.route('/vote/<int:answer_id>/')
@login_required
def vote(answer_id):
    _answer = Answer.query.get_or_404(answer_id)
    if g.user == _answer.user:
        flash('본인이 작성한 글은 추천할수 없습니다')
    else:
        _answer.voter.append(g.user)
        db.session.commit()

    return redirect('{}#answer_{}'.format(
        url_for('question.detail', question_id=answer.question.id), answer.id))

"""

truck/views/question_views.py
from datetime import datetime

from flask import Blueprint, render_template, jsonify, request, url_for, session, g, flash
from werkzeug.utils import redirect

from truck import db
from truck.models import Category, Question, Answer, User
from truck.forms import QuestionForm, AnswerForm
from truck.views.auth_views import login_required
import markdown
from markupsafe import Markup

bp = Blueprint('question', __name__, url_prefix='/question')


@bp.route('/list/')
@login_required
def _list():
    page = request.args.get('page', type=int, default=1)
    kw = request.args.get('kw', type=str, default='')
    category_id = request.args.get('category_id', type=int, default=None)

    # 선택된 카테고리 가져오기 (없으면 None)
    category = Category.query.get(category_id) if category_id else None

    # 질문 리스트 필터링 (카테고리가 있을 경우)
    question_list = Question.query.order_by(Question.create_date.desc())

    if category:
        question_list = question_list.filter_by(category_id=category_id)

    # 검색어 필터링을 위한 함수
    def apply_search_filters(query, kw):
        if not kw:
            return query

        search = f'%{kw}%'
        sub_query = db.session.query(Answer.question_id, Answer.content, User.username) \
            .join(User, Answer.user_id == User.id).subquery()

        return query.join(User) \
            .outerjoin(sub_query, sub_query.c.question_id == Question.id) \
            .filter(
            Question.subject.ilike(search) |
            Question.content.ilike(search) |
            User.username.ilike(search) |
            sub_query.c.content.ilike(search) |
            sub_query.c.username.ilike(search)
        ).distinct()

    # 검색어가 있을 경우 검색 적용
    question_list = apply_search_filters(question_list, kw)

    # 페이지네이션 처리 (필터링된 질문 리스트로)
    question_list = question_list.paginate(page=page, per_page=10)

    # 모든 카테고리 목록 가져오기
    categories = Category.query.all()

    # 템플릿에 question_list, categories, 선택된 category 전달
    return render_template(
        'question/question_list.html',
        question_list=question_list,
        categories=categories,
        category=category,      # 선택된 카테고리
        page=page,
        kw=kw
    )


@bp.route('/detail/<int:question_id>/')
@login_required
def detail(question_id):
    form = AnswerForm()
    question = Question.query.get_or_404(question_id)
    question_content_html = Markup(markdown.markdown(question.content))

    # 질문에 연결된 카테고리 가져오기
    category = question.category  # Question 모델에 category가 ForeignKey로 연결되어 있다고 가정

    return render_template('question/question_detail.html',
                           question=question,
                           content=question_content_html,
                           form=form,
                           category=category)  # 카테고리 정보 추가


@bp.route('/create', methods=['GET', 'POST'])
@login_required
def create():
    form = QuestionForm()

    # POST 요청일 경우
    if request.method == 'POST' and form.validate_on_submit():
        subject = form.subject.data
        content = form.content.data
        category_id = request.form.get('category_id')  # category_id 가져오기

        # category_id 값이 없을 경우 처리
        if not category_id:
            flash('카테고리가 선택되지 않았습니다.')
            return redirect(url_for('question.create'))

        question = Question(
            subject=subject,
            content=content,
            user_id=g.user.id,
            create_date=datetime.now(),
            category_id=category_id  # 카테고리 설정
        )
        db.session.add(question)
        db.session.commit()

        return redirect(url_for('question._list', category_id=category_id))

    # GET 요청일 경우
    category_id = request.args.get('category_id')  # URL에서 category_id 가져오기
    category = Category.query.get(category_id)

    return render_template('question/question_form.html', form=form, category=category)


@bp.route('/modify/<int:question_id>', methods=('GET', 'POST'))
@login_required
def modify(question_id):
    question = Question.query.get_or_404(question_id)
    if g.user != question.user:
        flash('수정권한이 없습니다')
        return redirect(url_for('question.detail', question_id=question_id))
    if request.method == 'POST':  # POST 요청
        form = QuestionForm()
        if form.validate_on_submit():
            form.populate_obj(question)
            question.modify_date = datetime.now()  # 수정일시 저장
            db.session.commit()
            return redirect(url_for('question.detail', question_id=question_id))
    else:  # GET 요청
        form = QuestionForm(obj=question)
    return render_template('question/question_form.html', form=form)


@bp.route('/delete/<int:question_id>')
@login_required
def delete(question_id):
    question = Question.query.get_or_404(question_id)
    if g.user != question.user:
        flash('삭제권한이 없습니다')
        return redirect(url_for('question.detail', question_id=question_id))
    db.session.delete(question)
    db.session.commit()
    return redirect(url_for('question._list'))


@bp.route('/vote/<int:question_id>/', methods=['POST'])  # POST 요청으로 변경
@login_required
def vote(question_id):
    _question = Question.query.get_or_404(question_id)
    if g.user == _question.user:
        return jsonify({'success': False, 'message': '본인이 작성한 글은 추천할 수 없습니다.'})
    else:
        _question.voter.append(g.user)
        db.session.commit()
        return jsonify({'success': True, 'voter_count': len(_question.voter)})


@bp.route('/partial')
def partial_question_list():
    category_id = request.args.get('category_id', type=int, default=None)
    if category_id:
        questions = Question.query.filter_by(category_id=category_id).all()
    else:
        questions = Question.query.all()

    return render_template('partials/question_list.html', question_list=questions)



"""
@bp.route('/vote/<int:question_id>/')
@login_required
def vote(question_id):
    _question = Question.query.get_or_404(question_id)
    if g.user == _question.user:
        flash('본인이 작성한 글은 추천할수 없습니다')
    else:
        _question.voter.append(g.user)
        db.session.commit()
    return redirect(url_for('question.detail', question_id=question_id))
    
    
@bp.route('/questions')
@login_required
def question_list():
    category_id = request.args.get('category_id', type=int, default=None)
    categories = Category.query.filter(Category.id.in_([4, 3, 2, 1, 0])).all()
    questions = get_questions_by_category(category_id)
    category = Category.query.get(category_id) if category_id else None
    return render_template('question/question_list.html', categories=categories, question_list=questions, category=category)




@bp.route('/detail/<int:question_id>/')
@login_required
def detail(question_id):
    form = AnswerForm()
    question = Question.query.get_or_404(question_id)
    question_content_html = Markup(markdown.markdown(question.content))
    return render_template('question/question_detail.html', question=question, content=question_content_html, form=form)


"""

truck/templates/question/question_detail.html
{% extends 'base.html' %}
{% block content %}

<!-- 질문 내용 -->
<div class="container my-3" style="max-width: 70%;">
    <div style="display: flex; justify-content: space-between; align-items: center; width: 100%;">
        <!-- 제목 5% -->
        <div style="width: 9%;">
            <h3 class="border-bottom py-2" style="margin-bottom: 0px;"><strong>제목 :</strong></h3>
        </div>

        <!-- 내용 50% -->
        <div style="width: 71%;">
            <h3 class="border-bottom py-2" style="margin-bottom: 0px;">
                <strong>{{ question.subject }}</strong>
            </h3>
        </div>
        <div>
            <a href="{{ url_for('question._list', category_id=category.id if category else None) }}" class="btn btn-secondary">목록으로</a>
        </div>
    </div>

    <!-- Responsive table for mobile devices -->
    <div class="table-responsive">
        <div class="row my-3">
            <!-- 제목 9% + 71% 합계 80%-->
            <div class="card-body" style="padding-top: 0;">
                <div class="card-text">{{ question.content|safe }}</div>
            </div>

        <div class="col-6 d-flex justify-content-start mt-1">
            <a href="javascript:void(0)" data-uri="{{ url_for('question.vote', question_id=question.id) }}"
                    class="recommend btn btn-sm btn-outline-secondary" style="margin-right: 10px;"> 추천
                <span class="badge rounded-pill bg-success">{{ question.voter|length }}</span>
            </a>

            {% if g.user == question.user %}
            <a href="{{ url_for('question.modify', question_id=question.id) }}"
                    class="btn btn-sm btn-outline-secondary" style="margin-right: 10px;">수정</a>
            <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary"
                    data-uri="{{ url_for('question.delete', question_id=question.id) }}"
                        style="margin-right: 10px;">삭제</a>
            {% endif %}
        </div>

        <div class="badge bg-light text-dark p-2 ms-2 d-flex flex-column align-items-end"
                        style="width: 45%; font-size: 0.875rem;">
            <div class="mb-1">작성자 : {{ question.user.username }} &nbsp;&nbsp;&nbsp;&nbsp;
                    작성일자 : {{ question.create_date|datetime }}</div>
            {% if question.modify_date %}
            <div class="mb-1">수정일자 : {{ question.modify_date|datetime }}</div>
            {% endif %}
        </div>

    </div>

    <!-- 파스텔톤 보라색 선 -->
    <hr style="border: 0; height: 5px; background-color: #FF6600; width: 100%;">

    <!-- 답변 목록  style="color: #FF6600;"-->
    <h5 class="border-bottom my-3 py-2">
        <u><strong><font color="#FF6600;">[{{ question.answer_set|length }}]</font>
                개의 답변이 있습니다.</strong></u></h5>

    {% for answer in question.answer_set %}
        <a id="answer_{{ answer.id }}"></a>     <!--  앵커 엘리먼트를 추가  -->

    <div class="row my-3">
        <!-- 답변 번호와 내용: -->
        <div style="width: 80%;">
            <h3 class="border-bottom py-2">
                <strong>{{ loop.index }}</strong>  <!-- 답변 번호 -->
                <span style="font-size: 1rem; color: black;">
                    {{ answer.content|markdown }}  <!-- 답변 내용 -->
                </span>
            </h3>
        </div>
     </div>

     <div class="row my-3">
        <!-- 추천, 수정, 삭제 버튼을 바로 아래에 추가 -->
        <div class="col-6 d-flex justify-content-start mt-1">

            <a href="javascript:void(0)" data-uri="{{ url_for('answer.vote', answer_id=answer.id) }}"
                   class="recommend btn btn-sm btn-outline-secondary"
                        style="margin-right: 2px;"> 추천
                 <span class="badge rounded-pill bg-success">{{ answer.voter|length }}</span>
            </a>

            {% if g.user == answer.user %}
            <a href="{{ url_for('answer.modify', answer_id=answer.id) }}"
                    class="btn btn-sm btn-outline-secondary ms-2" style="margin-right: 2px;">수정</a>
            <a href="#" class="delete btn btn-sm btn-outline-secondary ms-2"
                    data-uri="{{ url_for('answer.delete', answer_id=answer.id) }}"
                        style="margin-right: 2px;">삭제</a>
            {% endif %}
        </div>

        <div class="badge bg-light text-dark p-2 ms-2 d-flex flex-column align-items-end"
                        style="width: 45%; font-size: 0.875rem;">
            <div class="mb-1">답변자: {{ answer.user.username }} &nbsp;&nbsp;&nbsp;&nbsp;
                    답변일자: {{ answer.create_date|datetime }}</div>
            {% if answer.modify_date %}
            <div class="mb-1">수정일자 : {{ answer.modify_date|datetime }}</div>
            {% endif %}
        </div>
    </div>  <!--  <div class="row my-3"> 의 끝 부분 -->

    {% endfor %}

    </div>

    <!-- 답변 등록 -->
    <form action="{{ url_for('answer.create', question_id=question.id) }}"
            method="post" class="my-3">
        {{ form.csrf_token }}

        {% if form.errors %}     <!-- 오류표시 Start -->
        <div class="alert alert-danger" role="alert">
            {% for field, errors in form.errors.items() %}
            <strong>{{ form[field].label }}</strong>
            <ul>
                {% for error in errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </ul>
            {% endfor %}
        </div>
        {% endif %}         <!-- 오류표시 End  style="background-color: #E6FFE6;"-->

        <div class="mb-3">
            <textarea {% if not g.user %}disabled{% endif %}
                name="content"  id="markdown-editor" class="form-control"
                    rows="10"></textarea>
        </div>

        <!-- SimpleMDE 마크다운 에디터 초기화 -->
        <script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
        <script>
            var simplemde = new SimpleMDE({ element: document.getElementById("markdown-editor") });
        </script>

        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>

</div>

{% endblock %}

{% block script %}
<script type='text/javascript'>
document.querySelectorAll('.recommend').forEach(button => {
    button.addEventListener('click', function(event) {
        event.preventDefault();  // 링크 기본 동작 막기
        const url = this.getAttribute('data-uri');  // 추천 요청할 URL

        fetch(url, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRFToken': '{{ csrf_token() }}'  // CSRF 보호 (필요 시)
            }
        })
        .then(response => response.json())
        .then(data => {
            if (data.success) {
                // 성공 시 추천 수 업데이트
                this.querySelector('.badge').textContent = data.voter_count;
            } else {
                alert(data.message);
            }
        })
        .catch(error => console.error('Error:', error));
    });
});


document.getElementById('content').addEventListener('focus', function() {
    this.value = this.value.trimStart(); // 앞의 공백을 제거합니다.
});


const delete_elements = document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});

const recommend_elements = document.getElementsByClassName("recommend");
Array.from(recommend_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 추천하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});


document.getElementById('content').addEventListener('input', function() {
    let text = this.value;
    let maxLineLength = 30; // 최대 30자

    // 텍스트를 배열로 나눕니다.
    let lines = text.split('\n');

    // 배열을 순회하면서 30자 이상인 라인을 처리합니다.
    for (let i = 0; i < lines.length; i++) {
        if (lines[i].length > maxLineLength) {
            // 30자 이전에 있는 가장 가까운 공백을 찾아서 줄바꿈
            let spaceIndex = lines[i].lastIndexOf(' ', maxLineLength);
            if (spaceIndex > -1) {
                lines[i] = lines[i].substring(0, spaceIndex) + '\n' + lines[i].substring(spaceIndex + 1);
            }
        }
    }

    // 처리된 텍스트를 다시 적용
    this.value = lines.join('\n');
});

</script>
{% endblock %}

truck/templates/question/question_form.html
{% extends 'base.html' %}
{% block content %}

<!-- 질문 등록 -->
<div class="container my-3" style="max-width: 70%;">
    <div class="scrollable-table-container">

    <h5 class="my-3 border-bottom pb-2">
        <strong>우리의 <font cont color="#CD426B;">
            관심사</font>를 등록해 봅시다</strong></h5>
    <form method="post" class="my-3">
         {{ form.csrf_token }}

        {% if category %}
            <input type="hidden" name="category_id" value="{{ category.id }}">
        {% else %}
            <input type="hidden" name="category_id" value="0">
        {% endif %}

         <!-- 오류표시 Start -->
         {% if form.errors %}
         <div class="alert alert-danger" role="alert">
            {% for field, errors in form.errors.items() %}
            <strong>{{ form[field].label }}</strong>
            <ul>
                {% for error in errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </ul>
            {% endfor %}
         </div>
         {% endif %}
         <!-- 오류표시 End -->

         <!-- 수작업으로 폼 작성하기 -->
         <div class="mb-3">
              <label for="subject"><h5>제목</h5></label>
              <input type="text" class="form-control" name="subject" id="subject"
                      style="background-color: #F0FFF0;"
                          value="{{ form.subject.data or '' }}" autofocus>
         </div>
         <div class="mb-3">
              <label for="content"><h5>내용</h5></label>
              <textarea class="form-control"
                        name="content" id="markdown-editor" rows="10">
                        {{ form.content.data or '' }}
              </textarea>
         </div>

        <!-- SimpleMDE 마크다운 에디터 초기화  style="background-color: #E6FFE6;"-->
        <script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
        <script>
            var simplemde = new SimpleMDE({ element: document.getElementById("markdown-editor") });
        </script>


        <div class="mb-3">
        <button type="submit" class="btn btn-primary">질문 등록하기</button>
        </div>

    </form>

    </div>
</div>

{% endblock %}