truck/views/company_views.py
import functools
from sqlalchemy import func
from datetime import datetime
from datetime import date
from flask import Blueprint, url_for, render_template, flash, request, redirect, session, g
from werkzeug.utils import redirect
from truck import db
from truck.models import Company, User
from truck.forms import CompanyForm, CompanyPeriodForm, DeleteForm, CompanyClassPeriodForm
from truck.views.auth_views import login_required

from flask_wtf.csrf import CSRFProtect
import logging

COMPANY_CLASS_CHOICES = {
    'R': '매출처',
    'P': '매입처'
}

bp = Blueprint('company', __name__, url_prefix='/company')


@bp.route('/create', methods=('GET', 'POST'))
@login_required
def create():
    form = CompanyForm()
    now_today = datetime.today().date()  # 오늘 날짜를 가져옵니다.
    today = datetime.today()
    user_id = session['user_id']  # 로그인된 사용자 ID

    if not user_id:
        flash("User is not logged in.")
        return redirect(url_for('auth.login'))

    if request.method == 'POST' and form.validate_on_submit():
        company = Company(register_date=form.register_date.data, company_class=form.company_class.data,
            business_no=form.business_no.data, firm=form.firm.data, president=form.president.data,
                zip=form.zip.data, address=form.address.data, business_status=form.business_status.data,
                    business_item=form.business_item.data, email=form.email.data, cellphone=form.cellphone.data,
                        tel=form.tel.data, fax=form.fax.data,  note=form.note.data, user_id=user_id)

        db.session.add(company)
        db.session.commit()
        flash(f'Company table {form.firm.data} added successfully.')

        return redirect(url_for('company.create', today=today))

    # 오늘 날짜로 입력된 모든 transport 데이터를 가져옵니다.
    companies = Company.query.filter(
        Company.register_date == now_today, Company.user_id == user_id
    ).all()

    return render_template('company/company_form.html', form=form, today=today,
                companies=companies, enumerate=enumerate)


@bp.route('/company_period', methods=['GET', 'POST'])
@login_required
def company_period():
    form = CompanyPeriodForm()
    companies = []
    user_id = session.get('user_id')  # 현재 로그인된 사용자 ID 가져오기

    if not user_id:
        flash("User is not logged in.")
        return redirect(url_for('auth.login'))

    if request.method == 'POST' and form.validate_on_submit():
        start_date = request. form['start_date']
        end_date = request.form['end_date']

        if start_date and end_date:
            try:
                start_date = datetime.strptime(start_date, '%Y-%m-%d')
                end_date = datetime.strptime(end_date, '%Y-%m-%d')

                companies = Company.query.filter(
                    Company.register_date.between(start_date, end_date), Company.user_id == user_id
                ).order_by(Company.register_date.desc()).all()

                if not companies:
                    flash('검색 결과가 없습니다.', 'warning')
                return render_template('company/company_period_results.html',
                        companies=companies, company_class_choices=COMPANY_CLASS_CHOICES,
                                enumerate=enumerate)

            except ValueError:
                flash('잘못된 날짜 형식입니다.', 'danger')
        else:
            flash('날짜를 모두 입력하세요.', 'warning')

    # GET 요청일 경우 검색 폼을 렌더링
    return render_template('company/company_period.html', form=form)


@bp.route('/company/modify/<int:company_id>', methods=['GET', 'POST'])
@login_required
def modify_company(company_id):
    company = Company.query.get_or_404(company_id)
    form = CompanyForm(obj=company)  # Company 객체로부터 초기값 설정
    user_id = session.get('user_id')  # 현재 로그인된 사용자 ID 가져오기

    if not user_id:
        flash("User is not logged in.")
        return redirect(url_for('auth.login'))

    if form.validate_on_submit():
        form.populate_obj(company)  # 폼 데이터를 Company 객체에 반영
        db.session.commit()
        flash('업체 정보가 수정되었습니다.', 'success')
        return redirect(url_for('company.company_period'))

    return render_template('company/company_modify.html', form=form, company=company)


@bp.route('/delete_company/<int:company_id>', methods=['GET', 'POST'])
@login_required
def delete_company(company_id):
    user_id = session.get('user_id')  # 현재 로그인된 사용자 ID 가져오기

    if not user_id:
        flash("User is not logged in.")
        return redirect(url_for('auth.login'))

    # 삭제할 비용 항목 가져오기
    company = Company.query.get_or_404(company_id)

    # 사용자가 해당 Company 항목의 소유자인지 확인
    if company.user_id != user_id:
        flash("You do not have permission to delete this cost entry.", 'danger')
        return redirect(url_for('company.company_period'))

    # 삭제 확인 폼
    form = DeleteForm()

    # POST 요청 및 폼 유효성 검사
    if request.method == 'POST':
        db.session.delete(company)
        db.session.commit()
        flash('Company entry deleted successfully.', 'success')
        return redirect(url_for('company.company_period'))

    # 삭제 확인 페이지 렌더링
    return render_template('company/company_delete.html', form=form, company=company)


@bp.route('/company_class_period', methods=['GET', 'POST'])
@login_required
def company_class_period():
    form = CompanyClassPeriodForm(company_class='P')  # 들여쓰기를 수정합니다.
    companies = None
    user_id = session.get('user_id')  # 현재 로그인된 사용자 ID 가져오기

    if not user_id:
        flash("User is not logged in.")
        return redirect(url_for('auth.login'))

    if request.method == 'POST' and form.validate_on_submit():
        company_class = form.company_class.data
        start_date = form.start_date.data
        end_date = form.end_date.data

        if start_date and end_date:
            try:
                start_date = datetime.combine(start_date, datetime.min.time())
                end_date = datetime.combine(end_date, datetime.max.time())

                # company 테이블에서 지정된 기간 동안의 데이터를 조회하고 역순으로 정렬
                companies = Company.query.filter(
                    Company.company_class == company_class,
                    Company.register_date.between(start_date, end_date),
                    Company.user_id == user_id
                ).order_by(Company.register_date.desc()).all()

                # 만약 특정 cost_class를 필터링하려는 경우

                if not companies:
                    flash('검색 결과가 없습니다.', 'warning')
                return render_template('company/company_class_results.html',
                        companies=companies, company_class_choices=COMPANY_CLASS_CHOICES,
                                company_class=company_class, enumerate=enumerate)
            except ValueError:
                flash('잘못된 날짜 형식입니다.', 'danger')
        else:
            flash('날짜를 모두 입력하세요.', 'warning')

    # GET 요청일 경우 검색 폼을 렌더링
    return render_template('company/company_class_period.html', form=form)

truck/templates/company/company_class_period.html
{% extends "base.html" %}
{% block content %}

<span style="margin-left: 20px;" id="current_datetime"></span>
<br>
<form method="post">
    {{ form.hidden_tag() }}
    {% include "form_errors.html" %}

<div class="container-fluid">
    <div class="scrollable-table-container">
        <table style="min-width: 1000px;" class="table table-bordered table-striped">
           <thead class="head-dark">
           <tr bgcolor="#ffddee">
                <td colspan="6" class="text-center"><h3>분류별 업체현황 검색</h3></td>
               <td>&nbsp;</td>
           </tr>
           <tr>
               <td style="width:10%" class="text-center"><label for="company_class"><strong>회사 분류:</strong></label></td>
               <td style="background-color: yellow; width:10%">
                   {{ form.company_class(class="form-control") }}
               </td>
               <td style="width:10%" class="text-center"><label for="start_date"><strong>시작 일자</strong></label></td>
               <td style="width:15%" class="text-center">{{ form.start_date(class="form-control") }}</td>
               <td style="width:10%" class="text-center"><label for="end_date"><strong>마지막 일자</strong></label></td>
               <td style="width:15%" class="text-center">{{ form.end_date(class="form-control") }}</td>
               <td style="width:33%">&nbsp;</td>
           </tr>
           </thead>
        </table>
    </div>
    <div>
        <button type="submit" class="btn btn-primary">{{ form.submit() }}</button>
    </div>
</div>

</form>

{% endblock %}

truck/templates/company/company_class_results.html
{% extends "base.html" %}
{% block content %}

<span style="margin-left: 20px;" id="current_datetime"></span>

<div class="container-fluid">
    <div class="scrollable-table-container">

    <h5 class="text-center" style="color: #0000FF;"> &nbsp;&nbsp;&nbsp;&nbsp;<strong>
        {{ company_class_choices[company_class] }} 업체 현황</strong></h5>

    {% if companies %}
    <table class="table table-bordered">
        <thead class="head-dark">
            <tr>
                <!-- Displaying the category name at the top -->
                <td colspan="11" align="left"><strong>
                    {{ company_class_choices[company_class] }} &nbsp;&nbsp; 업체 현황</strong></td>
            </tr>
            <tr>
                <th style="width:3%" class="text-center">NO</th>
                <th style="width:6%" class="text-center">등록 일자</th>
                <th style="width:8%" class="text-center">회사명</th>
                <th style="width:10%" class="text-center">사업자 등록번호</th>
                <th style="width:6%" class="text-center">대표자</th>
                <th style="width:15%" class="text-center">사업장 주소</th>
                <th style="width:8%" class="text-center">업태</th>
                <th style="width:8%" class="text-center">종목</th>
                <th style="width:15%" class="text-center">이메일</th>
                <th style="width:8%" class="text-center">TEL</th>
                <th style="width:8%" class="text-center">FAX</th>
            </tr>
        </thead>
        <tbody>
        <!-- Loop through the costs and only display rows where the cost_class matches the selected category -->
        {% set ns = namespace(num=0) %}
        {% for idx, company in enumerate(companies) %}
            {% if company.company_class == company_class %}
                {% set ns.num = ns.num + 1 %}
            <tr>
                <td align="center">{{ ns.num }}</td>
                <td align="center">{{ company.register_date }}</td>
                <td align="center">{{ company.firm }}</td>
                <td align="center">{{ company.business_no }}</td>
                <td align="center">{{ company.president }}</td>
                <td align="center">{{ company.address }}</td>
                <td align="center">{{ company.business_status }}</td>
                <td align="center">{{ company.business_item }}</td>
                <td align="center">{{ company.email }}</td>
                <td align="center">{{ company.tel }}</td>
                <td align="center">{{ company.fax }}</td>
            </tr>
             {% endif %}
        {% endfor %}
        </tbody>
    </table>
    {% else %}
        <p class="text-center">검색 결과가 없습니다.</p>

    {% endif %}

    </div>
</div>

{% endblock %}

truck/templates/company/company_delete.html
{% extends "base.html" %}
{% block content %}

<span style="margin-left: 20px;" id="current_datetime"></span>

<div class="container-fluid">
    <div class="scrollable-table-container">

    <h5 class="text-center" style="color: #0000FF;"> {{ company.firm }} &nbsp;&nbsp;&nbsp;&nbsp; 운송 삭제/취소</h5>
    <p>정말로 이 항목을 삭제 하시겠습니까?</p>

    <form method="post" action="{{ url_for('company.delete_company', company_id=company.id) }}">
        {{ form.hidden_tag() }} <!-- CSRF 토큰 포함 -->

        <button type="submit" class="btn btn-danger">삭제</button>
        <a href="{{ url_for('company.company_period') }}" class="btn btn-secondary">취소</a>
    </form>

    </div>
</div>

{% endblock %}

truck/templates/company/company_form.html
{% extends "base.html" %}
{% block content %}

<span style="margin-left: 20px;" id="current_datetime"></span>

<form method="post">
    {{ form.csrf_token }}
    {% include "form_errors.html" %}

<div class="container-fluid">
   <div class="scrollable-table-container">
     <table style="width:100%" class="table table-bordered table-striped">

        <thead class="head-dark">
        <tr bgcolor="#ffddee">
            <th colspan="2" class="text-center"><h6><strong>업체 등록</strong></h6></th>
            <th class="text-center" ><label for="register_date">등록 일자</label></th>
            <td colspan="2">
                <input type="date" class="form-control" name="register_date" id="register_date"
                       placeholder="yyyy-mm-dd" style="width: 160px;" required
                                value="{{ form.register_date.data or '' }}">
            </td>
            <th class="text-center"><label for="company_class">회사 분류:</label></th>
            <td colspan="2" style="background-color: yellow;">
            <select class="form-control" name="company_class" id="company_class">
                    <option value="R">매출처</option>
                    <option value="P">매입처</option>
                </select>
            </td>
            <th colspan="1">&nbsp;</th>
            <th colspan="5" class="text-center"><h6><strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;오늘 날짜 :
                {{ today|datetime('%Y-%m-%d') }} 시각 : {{ today|datetime('%H:%M:%S %p') }}
                        </strong></h6></th>
        </tr>

        <tr style="width:100%" bgcolor="#ddeeff">
            <th style="width:3%" class="text-center">NO</th>
            <th style="width:10%" class="text-center"><label for="firm">상호</label></th>
            <th style="width:10%" class="text-center"><label for="business_no">사업자 등록번호</label></th>
            <th style="width:5%" class="text-center"><label for="president">성명</label></th>
            <th style="width:5%" class="text-center"><label for="zip">우편번호</label></th>
            <th style="width:10%" class="text-center"><label for="address">사업장주소</label></th>
            <th style="width:5%" class="text-center"><label for="business_status">업태</label></th>
            <th style="width:5%" class="text-center"><label for="business_item">종목</label></th>
            <th style="width:12%" class="text-center"><label for="email">이메일</label></th>
            <th style="width:8%" class="text-center"><label for="cellphone">핸드폰번호</label></th>
            <th style="width:8%" class="text-center"><label for="tel">전화번호</label></th>
            <th style="width:8%" class="text-center"><label for="fax">팩스번호</label></th>
            <th style="width:6%" class="text-center"><label for="note">비고</label></th>
        </tr>
        </thead>

        <tr style="width:100%" bgcolor="#ffffdd">
            <td>{{ count }}1</td>
            <td><input type="text" class="form-control" name="firm" id="firm"
                   value="{{ form.firm.data or '' }}"></td>
            <td><input type="text" class="form-control" name="business_no" id="business_no"
                   value="{{ form.business_no.data or '' }}"></td>
            <td><input type="text" class="form-control" name="president" id="president"
                   value="{{ form.president.data or '' }}"></td>
            <td><input type="text" class="form-control" name="zip" id="zip"
                   value="{{ form.zip.data or '' }}"></td>
            <td><input type="text" class="form-control" name="address" id="address"
                   value="{{ form.address.data or '' }}"></td>
            <td><input type="text" class="form-control" name="business_status" id="business_status"
                       value="{{ form.business_status.data or '' }}"></td>
            <td><input type="text" class="form-control" name="business_item" id="business_item"
                   value="{{ form.business_item.data or '' }}"></td>
            <td><input type="text" class="form-control" name="email" id="email"
                       value="{{ form.email.data or '' }}"></td>
            <td><input type="text" class="form-control" name="cellphone" id="cellphone"
                   value="{{ form.cellphone.data or '' }}"></td>
            <td><input type="text" class="form-control" name="tel" id="tel"
                   value="{{ form.tel.data or '' }}"></td>
            <td><input type="text" class="form-control" name="fax" id="fax"
                   value="{{ form.fax.data or '' }}"></td>
            <td><input type="text" class="form-control" name="note" id="note"
                   value="{{ form.note.data or '' }}"></td>
        </tr>
        <tr>
            <td colspan="3">
                <button type="submit" class="btn btn-primary">등록하기</button>
            </td>
            <td colspan="8" align="center" style="vertical-align: bottom;">
                <h6><strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;오늘 날짜 : {{ today|datetime('%Y-%m-%d') }}
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;업체 등록 현황</strong></h6>
            </td>
            <td colspan="2" align="center">&nbsp;</td>
        </tr>

       {% if companies %}
            {% for idx, company in enumerate(companies) %}
        <tr>
            <td align="center">{{ idx + 1 }}</td>
            <td>{{ company.firm }}</td>
            <td align="center">{{ company.business_no }}</td>
            <td align="center">{{ company.president }}
            <td align="center">{{ company.zip }}</td>
            <td>{{ company.address }}</td>
            <td>{{ company.business_status }}</td>
            <td>{{ company.business_item }}</td>
            <td>{{ company.email }}</td>
            <td align="center">{{ company.cellphone }}</td>
            <td align="center">{{ company.tel }}</td>
            <td align="center">{{ company.fax }}</td>
            <td>{{ company.note }}</td>
        <tr>
            {% endfor %}
        {% endif %}

    </table>
</div>

</form>

{% endblock %}

truck/templates/company/company_modify.html
{% extends "base.html" %}
{% block content %}

<span style="margin-left: 20px;" id="current_datetime"></span>

<div class="container-fluid">
    <div class="scrollable-table-container">

    <h5 class="text-left" style="color: #0000FF;"> &nbsp; 업체 수정 </h5>
    <form method="post" action="{{ url_for('company.modify_company', company_id=company.id) }}">
        {{ form.csrf_token }}
        {% include "form_errors.html" %}
        {{ form.hidden_tag() }} <!-- CSRF 토큰 -->

        <table style="min-width: 1000px;" class="table table-bordered">
        <thead class="head-dark">

        <tr>
            <td style="width: 10%; text-align: left;">  <label for="register_date">등록 일자:</label></td>
            <td style="width: 25%; text-align: left;">
                <span>{{ company.register_date }}</span>
                <input type="hidden" name="register_date" value="{{ company.register_date }}">
                &nbsp;&nbsp;&nbsp;&nbsp;[등록 일자는 수정할 수 없습니다]
            </td>
            <td style="width: 65%;">&nbsp;</td>
        </tr>
        <tr>
            <td style="width: 10% text-align: left;"><label for="company_class">회사 분류:</label></td>
            <td style="width: 25%; text-align: left; background-color: yellow;">
                <select class="form-control" id="company_class" name="company_class" required>
                    <option value="R" {% if company.company_class == 'R' %}selected{% endif %}>매출처</option>
                    <option value="P" {% if company.company_class == 'P' %}selected{% endif %}>매입처</option>
                </select>
            </td>
            <td style="width: 65%;">&nbsp;</td>
        </tr>
        <tr>
            <td style="width: 10%; text-align: left;"><label for="business_no">사업자 번호:</label></td>
            <td style="width: 25%; text-align: left;"><input type="text" class="form-control" id="business_no" name="business_no" value="{{ company.business_no }}" required></td>
            <td style="width: 65%;">&nbsp;</td>
        </tr>
        <tr>
            <td style="width: 10%; text-align: left;"><label for="firm">업체명:</label></td>
            <td style="width: 25%; text-align: left;"><input type="text" class="form-control" id="firm" name="firm" value="{{ company.firm }}" required></td>
            <td style="width: 65%;">&nbsp;</td>
        </tr>
        <tr>
            <td style="width: 10%; text-align: left;"><label for="president">대표자:</label></td>
            <td style="width: 25%; text-align: left;"><input type="text" class="form-control" id="president" name="president" value="{{ company.president }}" required></td>
            <td style="width: 65%;">&nbsp;</td>
        </tr>
        <tr>
            <td style="width: 10%; text-align: left;"><label for="zip">우편 번호:</label></td>
            <td style="width: 25%; text-align: left;"><input type="text" class="form-control" id="zip" name="zip" value="{{ company.zip }}"></td>
            <td style="width: 65%;">&nbsp;</td>
        </tr>
        <tr>
            <td style="width: 10%; text-align: left;"><label for="address">주소:</label></td>
            <td style="width: 25%; text-align: left;"><input type="text" class="form-control" id="address" name="address" value="{{ company.address }}" required></td>
            <td style="width: 65%;">&nbsp;</td>
        </tr>
        <tr>
            <td style="width: 10%; text-align: left;"><label for="business_status">업태:</label></td>
            <td style="width: 25%; text-align: left;"><input type="text" class="form-control" id="business_status" name="business_status" value="{{ company.business_status }}" required></td>
            <td style="width: 65%;">&nbsp;</td>
        </tr>
        <tr>
            <td style="width: 10%; text-align: left;"><label for="business_item">종목:</label></td>
            <td style="width: 25%; text-align: left;"><input type="text" class="form-control" id="business_item" name="business_item" value="{{ company.business_item }}" required></td>
            <td style="width: 65%;">&nbsp;</td>
        </tr>
        <tr>
            <td style="width: 10%; text-align: left;"><label for="email">이메일:</label></td>
            <td style="width: 25%; text-align: left;"><input type="text" class="form-control" id="email" name="email" value="{{ company.email }}"></td>
            <td style="width: 65%;">&nbsp;</td>
        </tr>
        <tr>
            <td style="width: 10%; text-align: left;"><label for="cellphone">핸드폰:</label></td>
            <td style="width: 25%; text-align: left;"><input type="text" class="form-control" id="cellphone" name="cellphone" value="{{ company.cellphone }}"></td>
            <td style="width: 65%;">&nbsp;</td>
        </tr>
        <tr>
            <td style="width: 10%; text-align: left;"><label for="tel">전화번호:</label></td>
            <td style="width: 25%; text-align: left;"><input type="text" class="form-control" id="tel" name="tel" value="{{ company.tel }}"></td>
            <td style="width: 65%;">&nbsp;</td>
        </tr>
        <tr>
            <td style="width: 10%; text-align: left;"><label for="fax">fax 번호:</label></td>
            <td style="width: 25%; text-align: left;"><input type="text" class="form-control" id="fax" name="fax" value="{{ company.fax }}"></td>
            <td style="width: 65%;">&nbsp;</td>
        </tr>
        <tr>
            <td style="width: 10% text-align: left;"><label for="note">비고:</label></td>
            <td style="width: 25%; text-align: left;"><input type="text" class="form-control" id="note" name="note" value="{{ company.note }}"></td>
            <td style="width: 65%;">&nbsp;</td>
        </tr>
        <tr>
            <td>
                <button type="submit" class="btn btn-primary">수정</button>
            </td>
        </tr>
        </thead>
        </table>

    </form>

    </div>
</div>

{% endblock %}

truck/templates/company/company_period.html
{% extends "base.html" %}
{% block content %}

<span style="margin-left: 20px;" id="current_datetime"></span>

<form method="post">
    {{ form.hidden_tag() }}
    {% include "form_errors.html" %}

<div class="container-fluid">
    <div class="scrollable-table-container">
        <table style="min-width: 1000px;" class="table table-bordered table-striped">
           <thead class="head-dark">
           <tr bgcolor="#ffddee">
               <td colspan="4" class="text-center"><h3>기간별 &nbsp;&nbsp;&nbsp;&nbsp; 업체현황 검색</h3></td>
               <td>&nbsp;</td>
           </tr>
           <tr>
               <td style="width:10%" class="text-left"><label for="start_date"><strong>시작 일자</strong></label></td>
               <td style="width:15%" class="text-center">{{ form.start_date(class="form-control") }}</td>
               <td style="width:10%" class="text-center"><label for="end_date"><strong>마지막 일자</strong></label></td>
               <td style="width:15%" class="text-center">{{ form.end_date(class="form-control") }}</td>
               <td style="width:50%">&nbsp;</td>
           </tr>
           </thead>
        </table>
    </div>
    <div>
        <button type="submit" class="btn btn-primary">{{ form.submit() }}</button>
    </div>
</div>

</form>

{% endblock %}

truck/templates/company/company_period_results.html
{% extends "base.html" %}
{% block content %}

<span style="margin-left: 20px;" id="current_datetime"></span>

<div class="container-fluid">
    <div class="scrollable-table-container">
        <h5 class="text-center" style="color: #0000FF;">기간별 &nbsp;&nbsp;&nbsp;&nbsp; 업체현황</h5>
        {% if companies %}
        <table style="min-width: 1000px;" class="table table-bordered table-striped">
            <thead class="head-dark">
            <tr>
                <th style="width:3%" class="text-center">NO</th>
                <th style="width:8%" class="text-center">등록일</th>
                <th style="width:8%" class="text-center">회사분류</th>
                <th style="width:10%" class="text-center">사업자 번호</th>
                <th style="width:12%" class="text-center">업체명</th>
                <th style="width:8%" class="text-center">대표자</th>
                <th style="width:22%" class="text-center">주소</th>
                <th style="width:8%" class="text-center">업태</th>
                <th style="width:9%" class="text-center">종목</th>
                <th style="width:6%" class="text-center">수정</th>
                <th style="width:6%" class="text-center">삭제</th>
            </tr>
            </thead>
            <tbody>
                {% for idx, company in enumerate(companies) %}
            <tr>
                <td>{{ idx + 1 }}</td>
                <td class="text-center">{{ company.register_date }}</td>
                <td class="text-center">{{ company_class_choices[company.company_class] }}</td>
                <td class="text-center">{{ company.business_no }}</td>
                <td class="text-center">{{ company.firm }}</td>
                <td class="text-center">{{ company.president }}</td>
                <td class="text-center">{{ company.address }}</td>
                <td class="text-center">{{ company.business_status }}</td>
                <td class="text-center">{{ company.business_item }}</td>
                <td class="text-center"><a href="{{ url_for('company.modify_company', company_id=company.id) }}" class="btn btn-warning">수정</a></td>
                <td class="text-center"><a href="{{ url_for('company.delete_company', company_id=company.id) }}" class="btn btn-danger">삭제</a></td>
            </tr>
                {% endfor %}
            </tbody>
        </table>

        {% else %}
            <p class="text-center">검색 결과가 없습니다.</p>
        {% endif %}

    </div>
</div>

{% endblock %}