truck/views/cost_views.py
import functools
from sqlalchemy import func
from datetime import datetime
from flask import Blueprint, url_for, render_template, flash, request, redirect, session, g
from werkzeug.utils import redirect
from truck import db
from truck.models import Cost
from truck.forms import CostForm, CostPeriodForm, CostClassPeriodForm, DeleteForm
from truck.views.auth_views import login_required

from flask_wtf.csrf import CSRFProtect
import logging

COST_CLASS_CHOICES = {
    'D': '경유',
    'G': '휘발유',
    'E': '전기충전',
    'T': '차량관리',
    'N': '생필품',
    'M': '식대',
    'F': '면세품목',
    'O': '기타'
}

PAYMENT_CHOICES = {
    'E': '전자세금계산서',
    'P': '종이세금계산서',
    'S': '간이세금계산서',
    'C': '카드',
    'R': '간이영수증',
    'M': '현금영수증',
    'O': '기타'
}

bp = Blueprint('cost', __name__, url_prefix='/cost')


@bp.route('/cost/create/', methods=['GET', 'POST'])
@login_required
def create():
    costs = []  # Initialize costs to an empty list or appropriate default value

    form = CostForm()
    now_today = datetime.today().date()  # Today’s date
    today = datetime.today()
    user_id = session.get('user_id')    # 로그인된 사용자 ID

    if not user_id:
        flash("User is not logged in.")
        return redirect(url_for('auth.login'))

    if request.method == 'POST' and form.validate_on_submit():
        # 세션에서 올바른 사용자 ID가 있는지 확인
        # flash(f'Logged in user ID: {session.get("user_id")}')
        # flash(f'Logged in as: {g.user.username}')

        cost = Cost(cost_date=form.cost_date.data, cost_company=form.cost_company.data,
                cost_class=form.cost_class.data, statement=form.statement.data,
                        payment=form.payment.data, bank_card=form.bank_card.data,
                            cost_amount=form.cost_amount.data, memo=form.memo.data,
                                    user_id=user_id)

        db.session.add(cost)
        db.session.commit()
        flash(f'Cost table for {form.cost_company.data} added successfully.')

        # Retrieve costs only for the logged-in user
        costs = Cost.query.filter(
            Cost.cost_date == now_today, Cost.user_id == user_id
        ).all()

    return render_template('cost/cost_form.html', form=form,
                today=today, costs=costs, cost_class_choices=COST_CLASS_CHOICES,
                        payment_choices=PAYMENT_CHOICES, enumerate=enumerate)


@bp.route('/cost_period', methods=['GET', 'POST'])
@login_required
def cost_period():
    form = CostPeriodForm()
    costs = []
    user_id = session.get('user_id')  # 현재 로그인된 사용자 ID 가져오기

    if not user_id:
        flash("User is not logged in.")
        return redirect(url_for('auth.login'))

    if request.method == 'POST' and form.validate_on_submit():

        start_date = request.form['start_date']
        end_date = request.form['end_date']

        if start_date and end_date:
            try:
                start_date = datetime.strptime(start_date, '%Y-%m-%d')
                end_date = datetime.strptime(end_date, '%Y-%m-%d')

                costs = Cost.query.filter(
                    Cost.cost_date.between(start_date, end_date), Cost.user_id == user_id
                ).order_by(Cost.cost_date.desc()).all()

                if not costs:
                    flash('No records found for the selected period.', 'warning')

                return render_template('cost/cost_period_results.html',
                        costs=costs, cost_class_choices=COST_CLASS_CHOICES,
                                    payment_choices=PAYMENT_CHOICES, enumerate=enumerate)

            except ValueError:
                flash('Invalid date format.', 'danger')
        else:
            flash('Please enter both dates.', 'warning')

    return render_template('cost/cost_period.html', form=form)


@bp.route('/cost_modify/<int:id>', methods=['GET', 'POST'])
@login_required
def cost_modify(id):
    user_id = session.get('user_id')  # 현재 로그인된 사용자 ID 가져오기

    if not user_id:
        flash("User is not logged in.")
        return redirect(url_for('auth.login'))

    # 수정하려는 비용 항목 가져오기
    cost = Cost.query.get_or_404(id)

    # 사용자가 해당 비용 항목의 소유자인지 확인
    if cost.user_id != user_id:
        flash("You do not have permission to modify this cost entry.", 'danger')
        return redirect(url_for('cost.cost_period'))

    # 비용 수정 폼 생성 및 기존 값으로 초기화
    form = CostForm(obj=cost)

    if form.validate_on_submit():
        try:
            # 수정된 데이터 폼으로부터 가져와서 객체 필드에 일괄 적용
            form.populate_obj(cost)
            cost.modify_date = datetime.now()  # 수정한 날짜 저장

            db.session.commit()
            flash('경비 정보가 수정 되었습니다.', 'success')
            return redirect(url_for('cost.cost_period'))
        except Exception as e:
            db.session.rollback()
            flash(f'An error occurred while updating the cost entry: {str(e)}', 'danger')

    return render_template('cost/cost_modify.html', form=form, cost=cost)


@bp.route('/cost_delete/<int:id>', methods=['GET', 'POST'])
@login_required
def cost_delete(id):
    user_id = session.get('user_id')  # 현재 로그인된 사용자 ID 가져오기

    if not user_id:
        flash("User is not logged in.")
        return redirect(url_for('auth.login'))

    # 삭제할 비용 항목 가져오기
    cost = Cost.query.get_or_404(id)

    # 사용자가 해당 비용 항목의 소유자인지 확인
    if cost.user_id != user_id:
        flash("You do not have permission to delete this cost entry.", 'danger')
        return redirect(url_for('cost.cost_period'))

    # 삭제 확인 폼
    form = DeleteForm()

    # POST 요청 및 폼 유효성 검사
    if form.validate_on_submit():
        db.session.delete(cost)
        db.session.commit()
        flash('경비 정보가 삭제되었습니다.', 'success')
        return redirect(url_for('cost.cost_period'))  # 원하는 페이지로 리다이렉트

    # 삭제 확인 페이지 렌더링
    return render_template('cost/cost_delete.html', form=form, cost=cost)


@bp.route('/cost_class_period', methods=['GET', 'POST'])
@login_required
def cost_class_period():
    form = CostClassPeriodForm()
    costs = None
    total_cost_amount = 0
    user_id = session.get('user_id')  # 현재 로그인된 사용자 ID 가져오기

    if not user_id:
        flash("User is not logged in.")
        return redirect(url_for('auth.login'))

    if request.method == 'POST' and form.validate_on_submit():
        # Use form data directly instead of request.form
        cost_class = form.cost_class.data
        start_date = form.start_date.data
        end_date = form.end_date.data

        # Check that start_date and end_date are provided
        if start_date and end_date:
            try:
                # Convert start_date and end_date to datetime objects (optional if form already validates it)
                start_date = datetime.combine(start_date, datetime.min.time())
                end_date = datetime.combine(end_date, datetime.max.time())

                # Fetch cost records and total amount in a single query
                costs = Cost.query.filter(
                    Cost.cost_class == cost_class,
                    Cost.cost_date.between(start_date, end_date),
                    Cost.user_id == user_id
                ).order_by(Cost.cost_date.desc()).all()

                # Calculate total cost amount
                total_cost_amount = db.session.query(
                    func.sum(Cost.cost_amount)
                ).filter(
                    Cost.cost_class == cost_class,
                    Cost.cost_date.between(start_date, end_date),
                    Cost.user_id == user_id
                ).scalar() or 0  # Default to 0 if no results

                if not costs:
                    flash('검색 결과가 없습니다.', 'warning')

                return render_template('cost/cost_class_results.html',
                    costs=costs, total_cost_amount=total_cost_amount, cost_class=cost_class,
                        cost_class_choices=COST_CLASS_CHOICES,
                            payment_choices=PAYMENT_CHOICES, enumerate=enumerate)

            except ValueError:
                flash('Invalid date format.', 'danger')
        else:
            flash('Please enter both dates.', 'warning')

    return render_template('cost/cost_class_period.html', form=form)

truck/templates/cost/cost_class_period.html
{% extends "base.html" %}
{% block content %}

<span style="margin-left: 20px;" id="current_datetime"></span>

<form method="post">
    {{ form.hidden_tag() }}
    {% include "form_errors.html" %}

    <div class="container-fluid">
        <div class="scrollable-table-container">
            <table style="min-width: 1000px;" class="table table-bordered table-striped">
                <thead class="head-dark">
                <tr bgcolor="#ffddee">
                    <td colspan="6" class="text-center"><h3>분류별 경비현황 검색</h3></td>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td style="width:10%" class="text-center"><label for="cost_class"><strong>경비 분류:</strong></label></td>
                    <td width:10%">
                        {{ form.cost_class(class="form-control") }}  <!-- Link form field to Jinja2 form object -->
                    </td>
                    <td style="width:10%" class="text-center"><label for="start_date"><strong>시작 일자</strong></label></td>
                    <td style="width:15%" class="text-center">{{ form.start_date(class="form-control") }}</td>
                    <td style="width:10%" class="text-center"><label for="end_date"><strong>마지막 일자</strong></label></td>
                    <td style="width:15%" class="text-center">{{ form.end_date(class="form-control") }}</td>
                    <td style="width:30%">&nbsp;</td>
                </tr>
                </thead>
            </table>
        </div>
        <div>
            <button type="submit" class="btn btn-primary">{{ form.submit() }}</button>
        </div>

    </div>

</form>

{% endblock %}

truck/templates/cost/cost_class_results.html
{% extends "base.html" %}
{% block content %}

<span style="margin-left: 20px;" id="current_datetime"></span>

<div class="container-fluid">
    <div class="scrollable-table-container">

    <!-- Display the chosen cost_class in the heading -->
    <h5 class="text-center" style="color: #0000FF;"> &nbsp;&nbsp;&nbsp;&nbsp;
        기간별 &nbsp;&nbsp; {{ cost_class_choices[cost_class] }}  지출 현황</h5>

    {% if costs %}
    <table class="table table-bordered">
        <thead class="head-dark">
            <tr>
                <!-- Displaying the category name at the top -->
                <td colspan="8" align="left"><strong>
                    {{ cost_class_choices[cost_class] }}&nbsp;&nbsp; 지출 현황</strong></td>
            </tr>
            <tr>
                <th style="width:5%" class="text-center">NO</th>
                <th style="width:8%" class="text-center">경비 일자</th>
                <th style="width:12%" class="text-center">회사명</th>
                <th style="width:12%" class="text-center">거래 내역</th>
                <th style="width:12%" class="text-center">지불 방법</th>
                <th style="width:8%" class="text-center">카드 은행</th>
                <th style="width:8%" class="text-center">경비 금액</th>
                <th style="width:12%" class="text-center">비고</th>
            </tr>
        </thead>

        <!-- Initialize a namespace to track the row count and total cost -->
        {% set ns = namespace(num=0, total_cost=0) %}

        <!-- Loop through the costs and only display rows where the cost_class matches the selected category -->
        {% for idx, cost in enumerate(costs) %}
            {% if cost.cost_class == cost_class %}
                {% set ns.num = ns.num + 1 %}
                <tr>
                    <td align="center">{{ ns.num }}</td>
                    <td align="center">{{ cost.cost_date }}</td>
                    <td align="center">{{ cost.cost_company }}</td>
                    <td align="center">{{ cost.statement }}</td>
                    <td align="center">{{ payment_choices[cost.payment] }}</td>
                    <td align="center">{{ cost.bank_card }}</td>
                    <td align="right">{{ "{:,.0f}".format(cost.cost_amount) }}&nbsp;&nbsp;&nbsp;&nbsp;</td>
                    <!-- Sum up the total cost -->
                    {% set ns.total_cost = ns.total_cost + cost.cost_amount %}
                    <td align="center">{{ cost.memo }}</td>
                </tr>
            {% endif %}
        {% endfor %}

        <!-- Total cost summary row -->
        <tr>
            <td colspan="6" class="text-center"><strong>총금액</strong></td>
            <td align="right"><strong>{{ "{:,.0f}".format(ns.total_cost) }}&nbsp;&nbsp;&nbsp;&nbsp;</strong></td>
            <td></td>
        </tr>
    </table>

    {% else %}
        <!-- If no results were found -->
        <p class="text-center">검색 결과가 없습니다.</p>

    {% endif %}

    </div>
</div>

{% endblock %}

truck/templates/cost/cost_delete.html
{% extends "base.html" %}
{% block content %}

<span style="margin-left: 20px;" id="current_datetime"></span>

<div class="container-fluid">
    <div class="scrollable-table-container">
    <h5 class="text-center" style="color: #0000FF;"> {{ cost.cost_company }} &nbsp;&nbsp;&nbsp;&nbsp; 경비 삭제/취소</h5>
    <p>정말로 이 항목을 삭제 하시겠습니까?</p>

    <form method="post" action="{{ url_for('cost.cost_delete', id=cost.id) }}">
        {{ form.hidden_tag() }}

        <button type="submit" class="btn btn-danger">삭제</button>
        <a href="{{ url_for('cost.cost_period') }}" class="btn btn-secondary">취소</a>
    </form>

    </div>
</div>

{% endblock %}

truck/templates/cost/cost_form.html
{% extends "base.html" %}
{% block content %}

<span style="margin-left: 20px;" id="current_datetime"></span>

<form method="post">
    {{ form.csrf_token }}
    {% include "form_errors.html" %}

<div class="container-fluid">
    <div class="scrollable-table-container">
        <table style="min-width: 1000px;" class="table table-bordered table-striped">

        <thead class="head-dark">
        <tr bgcolor="#ffddee">
            <th colspan="6" class="text-center"><h6><strong>경비 입력</strong></h6></th>
            <th colspan="3" class="text-center"><h6><strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;오늘 날짜 :
                {{ today|datetime('%Y-%m-%d') }} 시각 : {{ today|datetime('%H:%M:%S %p') }}
                        </strong></h6></th>
        </tr>

        <tr style="width:100%" bgcolor="#ddeeff">
            <th style="width:3%" class="text-center">NO</th>
            <th style="width:10%" class="text-center" ><label for="cost_date">경비 일자</label></th>
            <th style="width:12%" class="text-center"><label for="cost_company">회사명</label></th>
            <th style="width:8%" class="text-center" ><label for="cost_class">경비 형태</label></th>
            <th style="width:15%" class="text-center"><label for="statement">거래 내역</label></th>
            <th style="width:10%" class="text-center" ><label for="payment">거래 방법</label></th>
            <th style="width:8%" class="text-center"><label for="bank_card">카드 은행</label></th>
            <th style="width:8%" class="text-center"><label for="cost_amount">금액</label></th>
            <th style="width:15%" class="text-center"><label for="memo">비고</label></th>
        </tr>
        </thead>

        <tr style="width:100%" bgcolor="#ffffdd">
            <td align="center">{{ count }}1</td>
            <td><input type="date" class="form-control" id="cost_date" name="cost_date" placeholder="yyyy-mm-dd" style="width: 160px;" required></td>
            <td><input type="text" class="form-control" id="cost_company" name="cost_company"></td>
            <td>
                <select class="form-control" id="cost_class" name="cost_class">
                    <option value="D">경유</option>
                    <option value="G">휘발유</option>
                    <option value="E">전기충전</option>
                    <option value="T">차량관리</option>
                    <option value="N">생필품</option>
                    <option value="M">식대</option>
                    <option value="F">면세품목</option>
                    <option value="O">기타</option>
                </select>
           </td>
           <td><input type="text" class="form-control" id="statement" name="statement"> </td>
           <td>
               <select class="form-control" id="payment" name="payment">
                    <option value="E">전자세금계산서</option>
                    <option value="P">종이세금계산서</option>
                    <option value="S">간이세금계산서</option>
                    <option value="C" selected>카드</option>
                    <option value="R">간이영수증</option>
                    <option value="M">현금영수증</option>
                    <option value="O">기타</option>
                </select>
           </td>
           <td><input type="text" class="form-control" id="bank_card" name="bank_card"></td>
           <td><input type="number" class="form-control" id="cost_amount" name="cost_amount"
                      min="0" max="10000000" step="1" required></td>
           <td><input type="text" class="form-control" id="memo" name="memo"></td>
        </tr>

        <tr>
            <td colspan="3" align="left">
                <button type="submit" class="btn btn-primary">경비 입력</button>
            </td>
            <td colspan="5" align="center" style="vertical-align: bottom;">
                <h6><strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;오늘 날짜 : {{ today|datetime('%Y-%m-%d') }}
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;경비 현황</strong></h6>
            </td>
            <td colspan="1" align="center">&nbsp;</td>
        </tr>

            {% if costs %}
            {% for idx, cost in enumerate(costs) %}
        <tr>
            <td align="center">{{ idx + 1 }}</td>
            <td>{{ cost.cost_date }}</td>
            <td>{{ cost.cost_company }}</td>
            <td class="text-center">{{ cost_class_choices[cost.cost_class] }}</td>
            <td>{{ cost.statement }}</td>
            <td class="text-center">{{ payment_choices[cost.payment] }}</td>
            <td class="text-center">{{ cost.bank_card }}</td>
            <td align="right">{{ "{:,.0f}".format(cost.cost_amount) }}&nbsp;&nbsp;</td>
            <td>{{ cost.memo }}</td>
        <tr>
            {% endfor %}
        {% endif %}

        </table>
    </div>
</div>
</form>

{% endblock %}

truck/templates/cost/cost_modify.html
{% extends "base.html" %}
{% block content %}

<span style="margin-left: 20px;" id="current_datetime"></span>

<div class="container-fluid">
    <div class="scrollable-table-container">

    <h5 class="text-left" style="color: #0000FF;"> &nbsp; 경비 수정 </h5>
    <form method="post" action="{{ url_for('cost.cost_modify', id=cost.id) }}">
        {{ form.csrf_token }}
        {% include "form_errors.html" %}

        <table style="min-width: 1000px;" class="table table-bordered">
        <thead class="head-dark">
        <tr>
            <td style="width: 10%; text-align: left;">  <label for="cost_date">경비 일자:</label></td>
            <td style="width: 25%; text-align: left;"><input type="date" class="form-control" id="cost_date" name="cost_date" value="{{ cost.cost_date }}" required></td>
            <td style="width: 65%;">&nbsp;</td>
        </tr>
        <tr>
            <td style="width: 10%; text-align: left;"><label for="cost_company">회사명:</label></td>
            <td style="width: 25%; text-align: left;"><input type="text" class="form-control" id="cost_company" name="cost_company" value="{{ cost.cost_company }}" required></td>
            <td style="width: 65%;">&nbsp;</td>
        </tr>
        <tr>
            <td style="width:10% text-align: left;"><label for="cost_class">경비 형태:</label></td>
            <td style="width: 25%; text-align: left; background-color: yellow;">
                <select class="form-control" id="cost_class" name="cost_class" required>
                    <option value="D" {% if cost.cost_class == 'D' %}selected{% endif %}>경유</option>
                    <option value="G" {% if cost.cost_class == 'G' %}selected{% endif %}>휘발유</option>
                    <option value="E" {% if cost.cost_class == 'E' %}selected{% endif %}>전기충전</option>
                    <option value="T" {% if cost.cost_class == 'T' %}selected{% endif %}>차량관리</option>
                    <option value="N" {% if cost.cost_class == 'N' %}selected{% endif %}>생필품</option>
                    <option value="M" {% if cost.cost_class == 'M' %}selected{% endif %}>식대</option>
                    <option value="F" {% if cost.cost_class == 'F' %}selected{% endif %}>면세품목</option>
                    <option value="O" {% if cost.cost_class == 'O' %}selected{% endif %}>기타</option>
                </select>
            </td>
        </tr>
        <tr>
            <td style="width: 10%; text-align: left;"><label for="statement">거래 내역:</label></td>
            <td style="width: 25%; text-align: left;"><input type="text" class="form-control" id="statement" name="statement" value="{{ cost.statement }}" required></td>
            <td style="width: 65%;">&nbsp;</td>
        </tr>
        <tr>
            <td style="width:10% text-align: left;"><label for="payment">거래 방법:</label></td>
            <td style="width: 25%; text-align: left; background-color: yellow;">
                <select class="form-control" id="payment" name="payment" required>
                    <option value="E" {% if cost.payment == 'E' %}selected{% endif %}>전자세금계산서</option>
                    <option value="P" {% if cost.payment == 'P' %}selected{% endif %}>종이세금계산서</option>
                    <option value="S" {% if cost.payment == 'S' %}selected{% endif %}>간이세금계산서</option>
                    <option value="C" {% if cost.payment == 'C' %}selected{% endif %}>카드발급</option>
                    <option value="R" {% if cost.payment == 'R' %}selected{% endif %}>간이영수증</option>
                    <option value="M" {% if cost.payment == 'M' %}selected{% endif %}>현금영수증</option>
                    <option value="O" {% if cost.payment == 'O' %}selected{% endif %}>기타</option>
                </select>
        </tr>
        <tr>
            <td style="width: 10% text-align: left;"><label for="bank_card">카드 은행:</label></td>
            <td style="width: 25%; text-align: left;"><input type="text" class="form-control" id="bank_card" name="bank_card" value="{{ cost.bank_card }}"></td>
            <td style="width: 65%;">&nbsp;</td>
        </tr>
        <tr>
            <td style="width: 10% text-align: left;"><label for="bank_card">경비 금액:</label></td>
            <td style="width: 25%; text-align: left;"><input type="text" class="form-control" id="cost_amount" name="cost_amount" value="{{ cost.cost_amount }}"></td>
            <td style="width: 65%;">&nbsp;</td>
        </tr>
        <tr>
            <td style="width: 10% text-align: left;"><label for="memo">비고:</label></td>
            <td style="width: 25%; text-align: left;"><input type="text" class="form-control" id="memo" name="memo" value="{{ cost.memo }}"></td>
            <td style="width: 65%;">&nbsp;</td>
        </tr>
        <tr>
            <td>
                <button type="submit" class="btn btn-primary">수정</button>
            </td>
        </tr>
        </thead>
        </table>

    </form>

    </div>
</div>

{% endblock %}

truck/templates/cost/cost_period.html
{% extends "base.html" %}
{% block content %}

<span style="margin-left: 20px;" id="current_datetime"></span>

<form method="post">
    {{ form.hidden_tag() }}
    {% include "form_errors.html" %}

<div class="container-fluid">
    <div class="scrollable-table-container">
        <table style="min-width: 1000px;" class="table table-bordered table-striped">
           <thead class="head-dark">
           <tr bgcolor="#ffddee">
                <td colspan="4" class="text-center"><h3>기간별 &nbsp;&nbsp;&nbsp;&nbsp; 경비현황 검색</h3></td>
               <td>&nbsp;</td>
           </tr>
           <tr>
               <td style="width:10%" class="text-left"><label for="start_date"><strong>시작 일자</strong></label></td>
               <td style="width:15%" class="text-center">{{ form.start_date(class="form-control") }}</td>
               <td style="width:10%" class="text-center"><label for="end_date"><strong>마지막 일자</strong></label></td>
               <td style="width:15%" class="text-center">{{ form.end_date(class="form-control") }}</td>
               <td style="width:50%">&nbsp;</td>
           </tr>
           </thead>
        </table>
    </div>
    <div>
        <button type="submit" class="btn btn-primary">{{ form.submit() }}</button>
    </div>
</div>

</form>

{% endblock %}

truck/templates/cost/cost_period_results.html
{% extends "base.html" %}
{% block content %}

<span style="margin-left: 20px;" id="current_datetime"></span>

<div class="container-fluid">
    <div class="scrollable-table-container">
        <h5 class="text-center" style="color: #0000FF;">기간별 &nbsp;&nbsp;&nbsp;&nbsp; 경비현황</h5>
        {% if costs %}

        <table style="min-width: 1000px;" class="table table-bordered table-striped">
            <thead class="head-dark">
            <tr>
                <th style="width:5%" class="text-center">NO</th>
                <th style="width:8%" class="text-center">경비 일자</th>
                <th style="width:12%" class="text-center">회사명</th>
                <th style="width:10%" class="text-center">경비 형태</th>
                <th style="width:12%" class="text-center">거래 내역</th>
                <th style="width:10%" class="text-center">거래 방법</th>
                <th style="width:8%" class="text-center">카드 은행</th>
                <th style="width:8%" class="text-center">경비 금액</th>
                <th style="width:12%" class="text-center">비고</th>
                <th style="width:5%" class="text-center">수정</th>
                <th style="width:5%" class="text-center">삭제</th>
            </tr>
            </thead>
            <tbody>
                {% set ns = namespace(total_cost = 0) %}
                {% for idx, cost in enumerate(costs) %}
            <tr>
                <td align="center">{{ idx + 1 }}</td>
                <td align="center">{{ cost.cost_date }}</td>
                <td align="center">{{ cost.cost_company }}</td>
                <td align="center">{{ cost_class_choices[cost.cost_class] }}</td>
                <td align="center">{{ cost.statement }}</td>
                <td align="center">{{ payment_choices[cost.payment] }}</td>
                <td align="center">{{ cost.bank_card }}</td>
                <td align="center">{{ "{:,.0f}".format(cost.cost_amount) }}&nbsp;&nbsp;&nbsp;&nbsp;</td>
                {% set ns.total_cost = ns.total_cost + cost.cost_amount %}
                <td align="center">{{ cost.memo }}</td>
                <td><a href="{{ url_for('cost.cost_modify', id=cost.id) }}" class="btn btn-warning btn-sm">수정</a></td>
                <td><a href="{{ url_for('cost.cost_delete', id=cost.id) }}" class="btn btn-danger btn-sm">삭제</a></td>
            </tr>
                {% endfor %}
            <tr>
                <td colspan="7" class="text-center">총 금액</td>
                <td align="center">{{ "{:,.0f}".format(ns.total_cost) }}&nbsp;&nbsp;&nbsp;</td>
                <td colspan="3"></td>
            </tr>
            </tbody>
        </table>

        {% else %}
            <p class="text-center">검색 결과가 없습니다.</p>
        {% endif %}

    </div>
</div>

{% endblock %}