truck/models.py
from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash
from itsdangerous import URLSafeTimedSerializer
from flask import current_app
from . import db

# 중간 테이블 정의 (Question 및 Answer의 추천 기능을 위한 테이블)
question_voter = db.Table(
    'question_voter',
    db.Column('user_id', db.Integer, db.ForeignKey('user.id', ondelete='CASCADE'), primary_key=True),
    db.Column('question_id', db.Integer, db.ForeignKey('question.id', ondelete='CASCADE'), primary_key=True)
)

answer_voter = db.Table(
    'answer_voter',
    db.Column('user_id', db.Integer, db.ForeignKey('user.id', ondelete='CASCADE'), primary_key=True),
    db.Column('answer_id', db.Integer, db.ForeignKey('answer.id', ondelete='CASCADE'), primary_key=True)
)

# 카테고리 모델 정의
class Category(db.Model):
    __tablename__ = 'category'  # 테이블 이름이 일치해야 함
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False, unique=True)

    def __repr__(self):
        return f'<Category {self.name}>'

# 질문 모델 정의
class Question(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    subject = db.Column(db.String(200), nullable=False)
    content = db.Column(db.Text(), nullable=False)
    create_date = db.Column(db.DateTime(), nullable=False, default=datetime.now)
    modify_date = db.Column(db.DateTime(), nullable=True)
    # 사용자 및 추천 기능
    user_id = db.Column(db.Integer, db.ForeignKey('user.id', ondelete='CASCADE'), nullable=False)
    category_id = db.Column(db.Integer, db.ForeignKey('category.id'), nullable=False)
    voter = db.relationship('User', secondary=question_voter, backref=db.backref('question_voter_set'))

    user = db.relationship('User', backref=db.backref('question_set'))
    category = db.relationship('Category', backref=db.backref('question_set'))

    def __repr__(self):
        return f'<Question {self.subject}>'

# 답변 모델 정의
class Answer(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    content = db.Column(db.Text(), nullable=False)
    create_date = db.Column(db.DateTime(), nullable=False, default=datetime.now)
    modify_date = db.Column(db.DateTime(), nullable=True)

    # 질문과 답변 간의 관계
    question_id = db.Column(db.Integer, db.ForeignKey('question.id', ondelete='CASCADE'), nullable=False)
    question = db.relationship('Question', backref=db.backref('answer_set', cascade='all, delete-orphan'))

    # 사용자 및 추천 기능
    user_id = db.Column(db.Integer, db.ForeignKey('user.id', ondelete='CASCADE'), nullable=False)
    user = db.relationship('User', backref=db.backref('answer_set'))
    voter = db.relationship('User', secondary=answer_voter, backref=db.backref('answer_voter_set'))

    def __repr__(self):
        return f'<Answer {self.content[:15]}>'


class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    register_date = db.Column(db.Date, nullable=False)
    modify_date = db.Column(db.DateTime(), nullable=True)
    cancel_date = db.Column(db.DateTime(), nullable=True)
    deposit_date = db.Column(db.DateTime(), nullable=True)
    username = db.Column(db.String(32), unique=True, nullable=False)
    password = db.Column(db.String(255), nullable=False)
    truck_name = db.Column(db.String(16))
    truck_no = db.Column(db.String(12), nullable=False)
    truck_class = db.Column(db.String(12))
    truck_ton = db.Column(db.Numeric(precision=3, scale=1), nullable=True)
    business_no = db.Column(db.String(12), nullable=False)
    company = db.Column(db.String(32), nullable=False)
    member_name = db.Column(db.String(16), nullable=False)
    zip = db.Column(db.String(6))
    address = db.Column(db.String(56))
    business_status = db.Column(db.String(16), nullable=False)
    business_item = db.Column(db.String(16), nullable=False)
    email = db.Column(db.String(64), unique=True, nullable=True)    # nullable=True로 설정
    cellphone = db.Column(db.String(13), nullable=False)
    tel = db.Column(db.String(12))
    fax = db.Column(db.String(12))
    bank_name = db.Column(db.String(24))
    bank_no = db.Column(db.String(24))
    bank_account = db.Column(db.String(16))
    description = db.Column(db.String(32))
    is_admin = db.Column(db.Boolean, default=False)

    payments = db.relationship('MembershipPayment', backref='user', lazy=True)

    @staticmethod
    def verify_token(token):
        """토큰 검증 후 사용자 반환"""
        s = URLSafeTimedSerializer(current_app.config['SECRET_KEY'])
        try:
            data = s.loads(token)  # 토큰 디코딩
            user_id = data.get('user_id')  # 'user_id'로 저장한 값을 추출
            #print(f"Decoded user_id: {user_id}")  # user_id 출력해서 확인
        except:
            return None  # 토큰이 유효하지 않거나 만료됨

        return User.query.get(user_id)

    # 비밀번호 설정 메서드
    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    # 비밀번호 검증 메서드
    def check_password(self, password):
        return check_password_hash(self.password_hash, password)


class MembershipPayment(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)  # User와의 관계
    payment_date = db.Column(db.Date, nullable=False)  # 회비 입금일자
    payment_amount = db.Column(db.Integer, nullable=False)  # 입금금액
    suspension_date = db.Column(db.Date, nullable=True)  # 정지일자 (가입일자 + 6개월)
    modify_date = db.Column(db.DateTime(), nullable=True)
    annotation = db.Column(db.String(32))


class Transport(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    trans_date = db.Column(db.Date, nullable=True)
    modify_date = db.Column(db.DateTime(), nullable=True)
    trans_company = db.Column(db.String(32), nullable=True)
    consignor = db.Column(db.String(32), nullable=True)
    load_region = db.Column(db.String(64), nullable=True)
    unload_date = db.Column(db.Date, nullable=True)
    consignee = db.Column(db.String(32), nullable=True)
    unload_region = db.Column(db.String(64), nullable=True)
    terms = db.Column(db.String(2), nullable=False)
    trans_amount = db.Column(db.Integer, nullable=False)
    payment = db.Column(db.String(1), nullable=True)
    trans_set_date = db.Column(db.Date, nullable=True)
    brokerage_fee = db.Column(db.Integer, nullable=True)
    brokerage_date = db.Column(db.Date, nullable=True)
    trans_type = db.Column(db.String(1), nullable=False)
    comment = db.Column(db.String(32), nullable=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id', ondelete='CASCADE'), nullable=False)


class Cost(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    cost_date = db.Column(db.Date, nullable=False)
    modify_date = db.Column(db.DateTime(), nullable=True)
    cost_company = db.Column(db.String(32), nullable=False)
    cost_class = db.Column(db.String(1), nullable=False)
    statement = db.Column(db.String(32))
    payment = db.Column(db.String(1), nullable=False)
    bank_card = db.Column(db.String(32))
    cost_amount = db.Column(db.Integer)
    memo = db.Column(db.String(32), nullable=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id', ondelete='CASCADE'), nullable=False)

    COST_CLASS_CHOICES = {
        'D': '경유',
        'G': '휘발유',
        'E': '전기충전',
        'T': '차량관리',
        'N': '생필품',
        'M': '식대',
        'F': '면세품목',
        'O': '기타'
    }

    PAYMENT_CHOICES = {
        'E': '전자세금계산서',
        'P': '종이세금계산서',
        'S': '간이세금계산서',
        'C': '카드발급',
        'R': '간이영수증',
        'M': '현금영수증',
        'O': '기타'
    }


class Company(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    register_date = db.Column(db.Date, nullable=False)
    modify_date = db.Column(db.DateTime(), nullable=True)
    company_class = db.Column(db.String(1), nullable=False)
    business_no = db.Column(db.String(12), nullable=False)
    firm = db.Column(db.String(32), nullable=False)
    president = db.Column(db.String(16), nullable=True)
    zip = db.Column(db.String(6))
    address = db.Column(db.String(56))
    business_status = db.Column(db.String(16), nullable=True)
    business_item = db.Column(db.String(16), nullable=True)
    email = db.Column(db.String(64))
    cellphone = db.Column(db.String(13), nullable=True)
    tel = db.Column(db.String(12))
    fax = db.Column(db.String(12))
    note = db.Column(db.String(32), nullable=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id', ondelete='CASCADE'), nullable=False)

truck/views/auth_views.py
import functools

from datetime import datetime
from flask import Blueprint, url_for, render_template, redirect, flash, request, session, g
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect
from truck import db
from truck.models import User
from truck.forms import UserCreateForm, UserLoginForm, CancelForm, UserModifyForm, UserForgotForm, UserResetForm
from flask_wtf.csrf import CSRFProtect
import logging

from flask import current_app
from truck import Mail
from truck.email import send_reset_email, get_reset_token

bp = Blueprint('auth', __name__, url_prefix='/auth')

@bp.route('/terms', methods=['GET'])
def terms():
    return render_template('auth/terms.html')

@bp.route('/signup/', methods=('GET', 'POST'))
def signup():
    form = UserCreateForm()
    truck_ton_value = form.truck_ton.data if form.truck_ton.data else 0
    email_value = form.email.data.strip() if form.email.data and form.email.data.strip() != '' else None

    if request.method == 'POST' and form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if not user:
            today = datetime.today().strftime("%Y-%m-%d")
            user = User(register_date=today,
                        username=form.username.data,
                        password=generate_password_hash(form.password1.data),
                        truck_name=form.truck_name.data,
                        truck_no=form.truck_no.data,
                        truck_class=form.truck_class.data,
                        truck_ton=truck_ton_value,
                        business_no=form.business_no.data,
                        company=form.company.data,
                        member_name=form.member_name.data,
                        zip=form.zip.data,
                        address=form.address.data,
                        business_status=form.business_status.data,
                        business_item=form.business_item.data,
                        email=email_value,
                        cellphone=form.cellphone.data,
                        tel=form.tel.data,
                        fax=form.fax.data,
                        bank_name=form.bank_name.data,
                        bank_no=form.bank_no.data,
                        bank_account=form.bank_account.data,
                        description=form.description.data)

            db.session.add(user)
            db.session.commit()
            return redirect(url_for('main.index'))

    return render_template('auth/signup.html', form=form)

@bp.route('/login/', methods=('GET', 'POST'))
def login():
    form = UserLoginForm()

    if request.method == 'POST' and form.validate_on_submit():
        error = None
        user = User.query.filter_by(username=form.username.data).first()

        if not user:
            error = "존재하지 않는 회원입니다. 다시 로그인하여 주시기 바랍니다."
        elif not check_password_hash(user.password, form.password.data):
            error = "비밀번호가 올바르지 않습니다. 다시 로그인하여 주시기 바랍니다."

        if error is None:
            session.clear()
            session['user_id'] = user.id
            #flash(f'Logged in user ID: {session["user_id"]}')

            # 세션 및 g.user 확인
            g.user = user  # g.user에 현재 로그인한 사용자 저장

            if user.is_admin:  # 관리자인 경우
                return redirect(url_for('admin.manage_users'))
            else:
                # `next` 매개변수를 사용해 안전한 리다이렉트 처리
                _next = request.args.get('next')
                if not _next or url_parse(_next).netloc != '':  # 안전한 리다이렉트 검사
                    _next = url_for('transport.create')
                return redirect(_next)

        flash(error)

    # 이 부분이 추가되었습니다. GET 요청 또는 폼 검증 실패 시, 로그인 페이지를 렌더링합니다.  *** 줄맞춤이 중요하다.
    return render_template('auth/login.html', form=form)


@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')
    if user_id is None:
        g.user = None
    else:
        g.user = User.query.get(user_id)


@bp.route('/logout/')
def logout():
    session.clear()
    return redirect(url_for('main.index'))


def login_required(view):        # 사용자가 없거나, cancel_date가 있을 경우
    @functools.wraps(view)
    def wrapped_view(*args, **kwargs):
        if g.user is None or g.user.cancel_date is not None:
            _next = request.url if request.method == 'GET' else ''
            return redirect(url_for('auth.login', next=_next))
        return view(*args, **kwargs)
    return wrapped_view


@bp.route('/member_modify/', methods=['GET', 'POST'])
@login_required
def member_modify():
    user = User.query.get(session['user_id'])  # 현재 로그인된 사용자 ID로 사용자 정보 가져오기
    form = UserModifyForm(obj=user)  # 사용자 데이터를 사용해 폼 초기화
    truck_ton_value = form.truck_ton.data if form.truck_ton.data else 0
    email_value = form.email.data.strip() if form.email.data is not None else None

    if form.validate_on_submit():
        # 사용자가 입력한 데이터를 user 객체에 한 번에 매핑
        fields = [
            'username', 'truck_name', 'truck_no', 'truck_class', 'truck_ton',
            'business_no', 'company', 'member_name', 'zip', 'address',
            'business_status', 'business_item', 'email', 'cellphone', 'tel',
            'fax', 'bank_name', 'bank_no', 'bank_account', 'description'
        ]

        for field in fields:
            setattr(user, field, getattr(form, field).data)  # form에서 값을 가져와 user 객체에 설정

        # 비밀번호 변경 시에만 업데이트
        if form.password1.data:
            user.password = generate_password_hash(form.password1.data)

        # 수정 날짜 설정
        user.modify_date = datetime.now()
        truck_ton = truck_ton_value
        email = email_value

        db.session.commit()  # 데이터베이스에 변경 사항 저장
        flash('회원 정보가 수정되었습니다.', 'success')
        return redirect(url_for('main.index'))

    return render_template('auth/member_modify.html', user=user, form=form)


@bp.route('/member_cancel/', methods=['GET', 'POST'])
@login_required
def member_cancel():
    user_id = session.get('user_id')  # 현재 로그인된 사용자 ID 가져오기
    #form = CancelForm()

    if not user_id:
        flash("User is not logged in.")
        return redirect(url_for('auth.login'))

    # 탈퇴를 요청한 회원 id 가져오기
    user = User.query.get(session['user_id'])

    # 사용자가 해당 회원인지 확인
    if user.id != user_id:
        flash("You do not have permission to cancel this user entry.", 'danger')
        return redirect(url_for('main.index'))

    # 삭제 확인 폼
    form = CancelForm()

    # POST 요청 및 폼 유효성 검사
    if form.validate_on_submit():
        # user 테이블의 cancel_date에 현재 날짜를 입력
        user.cancel_date = datetime.now()  # 오늘 날짜로 cancel_date 설정
        db.session.commit()  # 변경사항을 DB에 저장
        flash('회원 탈퇴가 완료되었습니다.', 'success')
        return redirect(url_for('main.index'))

    return render_template('auth/member_cancel.html', form=form, user=user)


@bp.route('/forgot_password', methods=['GET', 'POST'])
def forgot_password():
    form = UserForgotForm()
    if request.method == 'POST' and form.validate_on_submit():
        email = request.form['email']
        member_name = request.form['member_name']
        cellphone = request.form['cellphone']
        truck_no = request.form['truck_no']

        print(f"member_name: {member_name}, cellphone: {cellphone}, truck_no: {truck_no}")

        user = User.query.filter(
            #User.email == email,
            User.member_name == member_name,
            User.cellphone == cellphone,
            User.truck_no == truck_no,
        ).first()

        if user:
            # 입력 받은 이메일을 가져옴
            # email = request.form['email']

            # 유저 테이블의 email 칼럼에 입력받은 이메일을 업데이트
            user.email = email
            db.session.commit()  # 변경 사항을 DB에 저장

            #print(f"user: {user}")

            # 이메일을 업데이트한 후, 해당 이메일로 비밀번호 재설정 링크 전송
            token = get_reset_token(user.id)  # user.id를 사용하여 토큰 생성
            send_reset_email(user, token)

            flash('비밀번호 재설정 링크가 이메일로 발송되었습니다.', 'success')
            return redirect(url_for('auth.reset_password', token=token))

        else:
            flash('해당 정보를 가진 회원을 찾을 수 없습니다.', 'danger')

    return render_template('auth/forgot_password.html', form=form)


@bp.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_password(token):
    form = UserResetForm()
    user = User.verify_token(token)  # verify_token에서 이미 User 객체를 반환하도록 수정

    if user is None:
        flash('Invalid or expired token', 'danger')
        return redirect(url_for('auth.forgot_password'))  # 토큰이 유효하지 않으면 리다이렉트
        print(f"user: {user}")  # user 출력해서 확인

    # 폼이 제출되었고 유효하면 비밀번호 변경 처리
    if form.validate_on_submit():
        new_password = form.password1.data
        user.set_password(new_password)  # 비밀번호 설정
        db.session.commit()  # 데이터베이스에 변경 사항 커밋
        flash('Your password has been reset.', 'success')
        return redirect(url_for('auth.login'))

    # 템플릿으로 폼 객체 전달
    return render_template('auth/reset_password.html', form=form, user=user, token=token)

truck/templates/base.html
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <!-- SimpleMDE CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">

    <title>Hello, truckman!</title>

    <style>
    .navbar-nav .nav-link {
        font-size: 1.25rem; /* 한 단계 큰 글씨 크기 */
        font-weight: bold;  /* 굵은 글씨체 */
    }
    </style>

</head>
<body>
    <!-- 네비게이션바 -->
    {% include "navbar.html" %}

    <!-- 기본 템플릿 안에 삽입될 내용 Start -->
    {% block content %}
    {% endblock %}

    <!-- 기본 템플릿 안에 삽입될 내용 End -->
    <!-- 공통 푸터 -->
    <footer>
        {% include "bottom.html" %}
    </footer>

    <!-- Bootstrap JS -->
    <script src="{{ url_for('static', filename='bootstrap.min.js') }}"></script>
    <!-- SimpleMDE JS -->
    <script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>

    <!-- 자바스크립트 Start -->
    {% block script %}
    {% endblock %}
    <!-- 자바스크립트 End -->

</body>
</html>

truck/templates/navbar.html
<!-- 네비게이션바 -->
<style>
    /* 기본적으로 툴팁 숨김 */
    #hover-item::after {
        content: '게시판 목록';  /* 툴팁 텍스트 */
        position: absolute;
        bottom: 100%;  /* 희망의 길 위에 표시 */
        left: 50%;
        transform: translateX(-50%);
        background-color: #a7c7e7;  /* 부드러운 파스텔 푸른색 */

        color: white;
        padding: 8px;       /* 패딩을 조금 키움 */
        font-size: 18px;    /* 글자 크기 키움 */
        border-radius: 5px;
        visibility: hidden;
        opacity: 0;
        transition: opacity 0.2s ease-in-out;
        white-space: nowrap;
    }

    /* 마우스 hover 시 툴팁 표시 */
    #hover-item:hover::after {
        visibility: visible;
        opacity: 1;
    }
</style>

<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
   <div class="container-fluid">
        <button class="navbar-toggler" type="button"
               data-bs-toggle="collapse"
               data-bs-target="#navbarSupportedContent"
               aria-controls="navbarSupportedContent"
               aria-expanded="false"
               aria-label="Toggle navigation">
           <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
           <ul class="navbar-nav me-auto mb-2 mb-lg-0">

           <!-- 관리자 대시보드 Dropdown -->
           {% if g.is_admin %}

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="adminDashboardDropdown" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">관리자</a>
                <ul class="dropdown-menu" aria-labelledby="adminDashboardDropdown">
                    <li><a class="dropdown-item" href="{{ url_for('admin.dashboard') }}">대시보드 홈</a></li>
                    <li><a class="dropdown-item" href="{{ url_for('admin.manage_users') }}">회원 관리</a></li>
                </ul>
            </li>

             <!-- 회비 관리 Dropdown -->
             <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="memberManagementDropdown" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">회비 관리</a>
                <ul class="dropdown-menu" aria-labelledby="memberManagementDropdown">
                    <li><a class="dropdown-item" href="{{ url_for('admin.payment_create') }}">회비 입력</a></li>
                    <li><a class="dropdown-item" href="{{ url_for('admin.payment_period') }}">회비 <span style="color: red;">[수정/삭제]</span></a></li>
                </ul>
             </li>
             {% endif %}

             {% if not g.is_admin %}
             <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">운송관리</a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="{{ url_for('transport.create') }}">운송 입력</a></li>
                    <li><a class="dropdown-item" href="{{ url_for('transport.trans_period', view_type='transport') }}">운송 <span style="color: red;"> [수정/삭제] </span> </a></li>
                    <li><a class="dropdown-item" href="{{ url_for('transport.trans_company', view_type='company') }}">거래처 운송현황</a></li>
                </ul>
             </li>
             {% endif %}

             <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">경비관리</a>
                <ul class="dropdown-menu" aria-labelledby="costManagementDropdown">
                    <li><a class="dropdown-item" href="{{ url_for('cost.create') }}">경비 입력</a></li>
                    <li><a class="dropdown-item" href="{{ url_for('cost.cost_period') }}">경비 <span style="color: red;">[수정/삭제]</span></a></li>
                    <li><a class="dropdown-item" href="{{ url_for('cost.cost_class_period') }}">분류별 경비현황</a></li>
                </ul>
             </li>

             <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">업체관리</a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="{{ url_for('company.create') }}">업체 등록</a></li>
                    <li><a class="dropdown-item" href="{{ url_for('company.company_period') }}">업체현황 <span style="color: red;"> [수정삭제] </span> </a></li>
                    <li><a class="dropdown-item" href="{{ url_for('company.company_class_period') }}">업체분류 검색</a></li>
                </ul>
             </li>

             <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">미수금관리</a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="{{ url_for('transport.trans_set_period') }}">전체 미수금입금</a></li>
                    <li><a class="dropdown-item" href="{{ url_for('transport.trans_company', view_type='set') }}">회사별 미수금입금</a></li>
                    <li><a class="dropdown-item" href="{{ url_for('transport.trans_company', view_type='company_set') }}">회사별 입금현황</a></li>
                    <li><a class="dropdown-item" href="{{ url_for('transport.trans_period', view_type='transport_set') }}">기간별 입금현황</a></li>
                    <li><a class="dropdown-item" href="{{ url_for('transport.trans_company', view_type='unpaid') }}">거래처 미수금현황</a></li>
                    <li><a class="dropdown-item" href="{{ url_for('transport.trans_period', view_type='unpaid') }}">전체 미수금현황</a></li>
                </ul>
             </li>

             <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">국세청 자료</a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="{{ url_for('balance.paper_period') }}">종이 세금계산서 제출 </a></li>
                    <li><a class="dropdown-item" href="{{ url_for('balance.elect_period') }}">전자 세금계산서 제출</a></li>
                    <li><a class="dropdown-item" href="{{ url_for('balance.tax_period') }}">경비 세금계산서 제출</a></li>
                </ul>
             </li>

             <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">대차대조표</a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="{{ url_for('balance.balance_period') }}">매출/매입자료</a></li>
                </ul>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" role="button"
                        href="{{ url_for('question._list', category_id=1) }}"
                            aria-expanded="false" style="color: #FF6600; position: relative;" id="hover-item">
                                희망의 길</a>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">유용한 사이트</a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="https://www.hometax.go.kr/websquare/websquare.html?w2xPath=/ui/pp/index_pp.xml" target="_blank">국세청</a></li>
                    <li><a class="dropdown-item" href="https://www.fordrivers.or.kr/main/main.do" target="_blank">화물복지 재단 </a></li>
                    <li><a class="dropdown-item" href="https://www.kotsa.or.kr" target="_blank">교통안전공단 </a></li>
                    <li><a class="dropdown-item" href="https://www.koroad.or.kr" target="_blank">한국도로교통공단 </a></li>
                    <li><a class="dropdown-item" href="https://www.ktdb.go.kr/www/selectBbsNttView.do?key=135&bbsNo=10&nttNo=439" target="_blank">국가교통DB</a></li>
                </ul>
            </li>

             {% if g.user %}
             <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">회원정보 관리</a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="{{ url_for('auth.member_modify') }}"><font color="blue">정보 수정</font></a></li>
                    <li><a class="dropdown-item" href="{{ url_for('auth.member_cancel') }}"><font color="red">회원 탈퇴</font></a></li>
                </ul>
             </li>

             <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('auth.logout') }}">[로그아웃]</a>
             </li>
             {% endif %}

           </ul>
       </div>
    </div>
</nav>